### PR TITLE
Update TJCOverallFHIR.cql

### PR DESCRIPTION
**Pull request by yanyanhu2**
Removed '// ' from definition of "Comfort Measures during Hospitalization", where it causes incorrect testing result

### CODE REVIEW

**Review by brynrhodes — CHANGES_REQUESTED** [review]
Hi Yanyan! Thank you for the submission, however, because the measure content in this repository is maintained by tooling from the MAT exports, if we were to accept this change, it would be overwritten by the tooling as soon as we did another refresh. Because the change is to a shared library, we would actually need updated exports for all the measures that have this library as a dependency. Is that a possibility?

**Comment by yanyanhu2** [comment]
Okay, I will be updating MAT and provide you an updated package. Where I can share the file with you, as I can not send out zip file?

**Comment by brynrhodes** [comment]
Hi @yanyanhu2 , you can commit them to your fork in the mat/bundles directory and then submit them as a PR.

**Comment by yanyanhu2** [comment]
Change is made to TJCOverall library

**Comment by brynrhodes** [comment]
Applied by extracting/refresh of 104.

**Pull request closed without merging**
